Created FirestoreDB class; Added Post retrieval and upload
ess-uofc/ess-schulichhub pull request #70
Opened 2021-02-09 22:55 UTC by lemohammed

Changelog:
/Models/firestore.ts
/Models/firebase.ts
/Models/Post.ts
/Models/Comment.ts
/app/routing.ts
/Component/loading.tsx

2021-02-09 23:37 UTC, rjb75 approved these changes
Great job @lemohammed! 🏆

2021-02-10 00:24 UTC, RatikKapoor requested changes
@lemohammed Just quickly edit your PR for the changelog and then 🚀 😄

2021-02-10 00:24 UTC, RatikKapoor commented on src/components/HomePostView.tsx
> +                ? posts.map((v, k) => {
😍

2021-02-10 00:38 UTC, RatikKapoor approved these changes
🚀

2021-02-10 00:38 UTC, merged